name: tattink_app
description: "TattInk - Dövme artistleri ile müşterileri bir araya getiren platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  # Icons & Fonts
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  
  # Firebase Core & Auth
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

  # Google Giriş Paketi Burada
  google_sign_in: 6.2.0  
  
  # Firebase Services
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3
  
  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  image: ^4.3.0
  
  # Location services
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  
  # Utilities
  url_launcher: ^6.3.1
  file_picker: ^8.1.4
  flutter_slidable: ^3.1.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  
  # UI
  google_nav_bar: ^5.0.6
  google_maps_flutter: ^2.9.0
  video_player: ^2.9.1
  carousel_slider: ^5.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # Projenin min_sdk değerine göre ayarla